# -*- coding: utf-8 -*-
"""picaso_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jOJDiXJf_816hFqDEEEzx6wgVkRrVBs
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Importing all libraries and modules.**"""

#importing all the libraries
import pandas as pd
import os
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import re
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torchvision.transforms as transforms
import seaborn as sns
from scipy.stats import skew, kurtosis
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler,RobustScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud
from sklearn.feature_selection import mutual_info_classif

"""**Loading the captions file**"""

import pandas as pd

file_path = '/content/drive/MyDrive/ROCO_data/data/train/radiology/captions.txt'

try:
    captions = pd.read_csv(file_path, sep='\t', header=None, names=['image_id', 'caption'])
    print("File loaded successfully!")
    print(captions.head())
except FileNotFoundError:
    print(f"Error: The file at {file_path} was not found.")
except pd.errors.EmptyDataError:
    print("Error: The file is empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""**Dataset Overview.**

"""

print("\n# Dataset Overview")
print(f"Shape of the dataset: {captions.shape}")
print("\nFirst 5 rows:")
print(captions.head())
print("\nColumns:")
print(list(captions.columns))
print("\nData Types:")
print(captions.dtypes)

"""**Handling Missing Values**"""

print("\n# Missing Values")
missing_values = captions.isnull().sum()
if missing_values.any():
    print("Columns with missing values and their counts:")
    print(missing_values[missing_values > 0])
else:
    print("No missing values found in the dataset.")

"""**Visualizing Missing Data**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.heatmap(captions.isnull(), cbar=False, cmap='viridis', linewidths=0.5, linecolor='white')
plt.title("Heatmap of Missing Values in the Dataset", fontsize=16, fontweight='bold', pad=15)
plt.xlabel("Columns", fontsize=12)
plt.ylabel("Rows", fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Descriptive Statistics**"""

print("\n# Summary Statistics")
if not captions.empty:
    print("\nSummary Statistics for Numeric Columns:")
    print(captions.describe())
    print("\nSummary Statistics for All Columns:")
    print(captions.describe(include='all'))
else:
    print("The dataset is empty. No summary statistics available.")

"""
**Descriptive Statistics for the 'caption' Column**"""

print("\n# Summary Statistics for 'caption' Column")
if 'caption' in captions.columns:
    if captions['caption'].notnull().any():
        print(captions['caption'].describe())
    else:
        print("The 'caption' column exists but contains only null values.")
else:
    print("The 'caption' column does not exist in the dataset.")

"""**Information about the 'caption' Column**"""

print("\n# Information about the 'caption' Column")
if 'caption' in captions.columns:
    print(f"Data Type: {captions['caption'].dtype}")
    print(f"Number of Non-Null Values: {captions['caption'].notnull().sum()}")
    print(f"Number of Null Values: {captions['caption'].isnull().sum()}")
    print(f"Unique Values: {captions['caption'].nunique()}")
else:
    print("The 'caption' column does not exist in the dataset.")

"""**Display the Last 10 Rows of the 'caption' Column**"""

print("\n# Last 10 Rows of the 'caption' Column")
if 'caption' in captions.columns:
    if not captions['caption'].empty:
        print(captions['caption'].tail(10))
    else:
        print("The 'caption' column exists but is empty.")
else:
    print("The 'caption' column does not exist in the dataset.")

"""**Value Counts for the 'caption' Column**"""

print("\n# Value Counts for the 'caption' Column")
if 'caption' in captions.columns:
    if not captions['caption'].empty:
        print(captions['caption'].value_counts())
    else:
        print("The 'caption' column exists but is empty.")
else:
    print("The 'caption' column does not exist in the dataset.")

"""**Count of Unique Values in the 'caption' Column**"""

print("\n# Count of Unique Values in the 'caption' Column")
if 'caption' in captions.columns:
    unique_count = captions['caption'].nunique()
    print(f"The number of unique captions is: {unique_count}")
else:
    print("The 'caption' column does not exist in the dataset.")

"""**Dropping Duplicates from the 'captions' DataFrame**"""

print("\n# Dropping Duplicates from the Dataset")
initial_count = captions.shape[0]
captions.drop_duplicates(inplace=True)
final_count = captions.shape[0]

duplicates_dropped = initial_count - final_count
print(f"Number of duplicates dropped: {duplicates_dropped}")

print("\nUpdated Dataset (First 5 rows):")
print(captions.head())

"""**Statistical Insights on Captions (Length)**"""

print("\n# Statistical Insights on Caption Lengths")
if 'caption' in captions.columns:
    caption_lengths = captions['caption'].apply(len)

    mean_length = caption_lengths.mean()
    median_length = caption_lengths.median()
    std_dev_length = caption_lengths.std()

    print(f"Caption Length - Mean: {mean_length:.2f}")
    print(f"Caption Length - Median: {median_length:.2f}")
    print(f"Caption Length - Standard Deviation: {std_dev_length:.2f}")
else:
    print("The 'caption' column does not exist in the dataset.")

import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew, kurtosis
s
plt.figure(figsize=(10, 5))
sns.histplot(caption_lengths, kde=True, bins=30, color='blue')
plt.title('Univariate Analysis: Distribution of Caption Lengths', fontsize=16)
plt.xlabel('Caption Length', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(True)
plt.show()
print("\n# Statistical Summary of Caption Lengths")
print(f"Caption Length - Mean: {caption_lengths.mean():.2f}")
print(f"Caption Length - Median: {caption_lengths.median():.2f}")
print(f"Caption Length - Standard Deviation: {caption_lengths.std():.2f}")
print(f"Caption Length - Skewness: {skew(caption_lengths):.2f}")
print(f"Caption Length - Kurtosis: {kurtosis(caption_lengths):.2f}")

if 'category' in captions.columns:
    plt.figure(figsize=(10, 5))
    sns.countplot(x='category', data=captions, palette='Set2')
    plt.title('Univariate Analysis: Category Distribution', fontsize=16)
    plt.xlabel('Category', fontsize=12)
    plt.ylabel('Count', fontsize=12)
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.show()
else:
    print("The 'category' column does not exist in the dataset.")

from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud
import matplotlib.pyplot as plt

if 'caption' in captions.columns:
    print("\n# Text Data Analysis")

    text_data = captions['caption'].dropna()
    vectorizer = CountVectorizer(stop_words='english')
    word_counts = vectorizer.fit_transform(text_data)
    word_counts_sum = word_counts.sum(axis=0)

    words = vectorizer.get_feature_names_out()
    word_freq = [(word, word_counts_sum[0, idx]) for word, idx in zip(words, range(len(words)))]
    word_freq = sorted(word_freq, key=lambda x: x[1], reverse=True)


    print("\nTop 10 Most Frequent Words:")
    for word, freq in word_freq[:10]:
        print(f"{word}: {freq}")


    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(' '.join(text_data))

    plt.figure(figsize=(10, 6))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title("Word Cloud", fontsize=16)
    plt.show()
else:
    print("The 'caption' column does not exist in the dataset.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# Clustering Captions
if 'caption' in captions.columns:
    print("\n# Clustering Captions")

    vectorizer = CountVectorizer(max_features=1000, stop_words='english')
    caption_features = vectorizer.fit_transform(captions['caption'])

    pca = PCA(n_components=2)
    reduced_features = pca.fit_transform(caption_features.toarray())


    kmeans = KMeans(n_clusters=5, random_state=42)
    clusters = kmeans.fit_predict(reduced_features)


    plt.figure(figsize=(10, 6))
    sns.scatterplot(x=reduced_features[:, 0], y=reduced_features[:, 1], hue=clusters, palette='viridis', legend='full')
    plt.title('Clustering Captions (PCA-reduced Features)', fontsize=16)
    plt.xlabel('PCA Component 1', fontsize=12)
    plt.ylabel('PCA Component 2', fontsize=12)
    plt.grid(True)
    plt.show()
else:
    print("The 'caption' column does not exist in the dataset.")

"""Calculate Caption Length and Add as a New Column"""

base_dir = '/content/drive/MyDrive/ROCO_data/data'
splits = ['train', 'test', 'validation']
categories = ['radiology', 'non-radiology']

data = []
for split in splits:
    for category in categories:
        category_dir = os.path.join(base_dir, split, category)
        captions_file = os.path.join(category_dir, 'captions.txt')

        if os.path.exists(captions_file):
            with open(captions_file, 'r', encoding='utf-8', errors='ignore') as file:
                for line in file:
                    image_id = line[:12]
                    caption = line[12:].strip()
                    label = category
                    data.append([image_id, caption, label, split])

df = pd.DataFrame(data, columns=['image_id', 'caption', 'label', 'split'])
df

if 'caption' in df.columns:
    df['caption_length'] = df['caption'].str.len()
    print("\n# Caption Length Column Added")
    print(df[['caption', 'caption_length']].head())
else:
    print("The 'caption' column does not exist in the DataFrame.")

sample_df = pd.DataFrame(data)
sample_df.head(5)

import matplotlib.pyplot as plt

split_counts = df['split'].value_counts()
plt.figure(figsize=(8, 6))
plt.pie(split_counts, labels=split_counts.index, autopct='%1.1f%%', startangle=140, colors=['red', 'green', 'blue'])
plt.title("Distribution of Train, Test, and Validation Splits")
plt.show()

label_counts = df['label'].value_counts()
plt.figure(figsize=(8, 6))
plt.pie(label_counts, labels=label_counts.index, autopct='%1.1f%%', startangle=140, colors=['magenta', 'yellow'])
plt.title("Distribution of Radiology and Non-Radiology Labels")
plt.show()

image_folder = '/content/drive/MyDrive/ROCO_data/data/train/radiology/images'
if os.path.exists(image_folder):
    print("\n# Image Data Analysis ")
    image_files = [os.path.join(image_folder, f) for f in os.listdir(image_folder) if f.endswith(('.png', '.jpg', '.jpeg'))]
    print(f"Number of images: {len(image_files)}")

    # Display Sample Images
    for i, image_file in enumerate(image_files[:5]):
        img = Image.open(image_file)
        plt.figure(figsize=(4, 4))
        plt.imshow(img)
        plt.axis('off')
        plt.title(f"Sample Image {i+1}")
        plt.show()

import os
import matplotlib.pyplot as plt
import torch
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
import textwrap

class RocoDataset(Dataset):
    def __init__(self, image_dir, caption_file, transform=None):
        self.image_dir = image_dir
        self.transform = transform

        with open(caption_file, 'r') as f:
            self.captions = f.readlines()

        self.image_filenames = sorted(os.listdir(image_dir))
    def __len__(self):
        return len(self.image_filenames)

    def __getitem__(self, idx):
        img_path = os.path.join(self.image_dir, self.image_filenames[idx])
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)
        caption = self.captions[idx].strip()
        return image, caption

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

image_dir = '/content/drive/MyDrive/ROCO_data/data/train/radiology/images'
caption_file = '/content/drive/MyDrive/ROCO_data/data/train/radiology/captions.txt'
roco_dataset = RocoDataset(image_dir, caption_file, transform=transform)
train_loader = DataLoader(roco_dataset, batch_size=8, shuffle=True)

def denormalize_image(tensor):
    mean = torch.tensor([0.485, 0.456, 0.406])
    std = torch.tensor([0.229, 0.224, 0.225])
    tensor = tensor * std[:, None, None] + mean[:, None, None]
    return tensor.permute(1, 2, 0).clamp(0, 1).numpy()

def show_batch_images(data_loader):
    data_iter = iter(data_loader)
    images, captions = next(data_iter)

    num_images = images.shape[0]
    cols = 4
    rows = (num_images // cols) + (num_images % cols > 0)

    fig, axes = plt.subplots(nrows=rows, ncols=cols, figsize=(20, rows * 5))
    axes = axes.flatten()

    for i in range(num_images):
        image = denormalize_image(images[i])
        axes[i].imshow(image)
        wrapped_caption = textwrap.fill(captions[i], width=40)
        axes[i].set_title(f"Caption: {wrapped_caption}", fontsize=10)
        axes[i].axis('off')

    for j in range(num_images, len(axes)):
        axes[j].axis('off')

    plt.tight_layout()
    plt.show()

print("Displaying a batch from train_loader:")
show_batch_images(train_loader)

from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image

base_model=VGG16(weights="imagenet")

from tensorflow.keras.preprocessing import image
model=Model(inputs=base_model.input,outputs=base_model.get_layer("block5_conv3").output)

def load_and_preprocess_image(img_path,target_size=(224,224)):
  img=image.load_img('/content/drive/MyDrive/ROCO_data/data/train/radiology/images/ROCO_81800.jpg',target_size=target_size)
  img_array=image.img_to_array(img)
  img_array=np.expand_dims(img_array,axis=0)
  img_array=preprocess_input(img_array)
  return img_array

img=image.load_img('/content/drive/MyDrive/ROCO_data/data/train/radiology/images/ROCO_81800.jpg',target_size=(224,224))
img_array=image.img_to_array(img)

img_array.shape

img_array=np.expand_dims(img_array,axis=0)
img_array.shape

feature_maps=model.predict(img_array)

n_features=feature_maps.shape[-1]
n_features

size=feature_maps.shape[1]
from PIL import Image

img_path='/content/drive/MyDrive/ROCO_data/data/train/radiology/images/ROCO_81808.jpg'
img=Image.open(img_path)
img.size

display_grid=np.zeros((size,size*n_features))
display_grid

for i in range(n_features):
  x=feature_maps[0,:,:,i]
  x-=x.mean()
  x/=(x.std()+1e-5)
  x*=64
  x+=128
  x=np.clip(x,0,255).astype(int)
  display_grid[:,i*size:(i+1)*size]=x

scale=20./n_features
plt.figure(figsize=(scale*n_features,scale))
plt.title("Feature Maps")
plt.grid(False)
plt.imshow(display_grid,aspect="auto")

from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import Model
import matplotlib.pyplot as plt

def plot_feature_maps(feature_maps, num_channels=16, figsize=(20, 20), colormap='viridis'):
    channels = feature_maps.shape[-1]
    num_channels = min(num_channels, channels)
    fig, axes = plt.subplots(1, num_channels, figsize=figsize)
    for i in range(num_channels):
        ax = axes[i]
        ax.imshow(feature_maps[0, :, :, i], cmap=colormap)
        ax.axis('off')
    plt.tight_layout()
    plt.show()

print(f"Feature map shape: {feature_maps.shape}")
plot_feature_maps(feature_maps, num_channels=16, figsize=(15, 10), colormap='plasma')

""" ANN"""

df

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=1000)
X=tfidf.fit_transform(df['caption']).toarray()
y=df['label']
X
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

"""**Split into Train, Validation, and Test Sets**"""

# Import necessary libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, roc_auc_score, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy
from keras.callbacks import EarlyStopping
import numpy as np

# tfidf the caption and create our X and y variables.
tfidf = TfidfVectorizer(max_features=1000)
X = tfidf.fit_transform(df['caption']).toarray()
y = df['label']

# Label encode y variable.
le = LabelEncoder()
y = le.fit_transform(y)

# Split the dataset into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

# Define the model
model = Sequential([
    Dense(128, activation='relu', kernel_regularizer=l2(0.01), input_shape=(X.shape[1],)),  # Increased units
    Dropout(0.5),
    Dense(64, activation='relu', kernel_regularizer=l2(0.01)),  # Increased units
    Dropout(0.4),  # Adjusted dropout rate
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Implement early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_val, y_val),
                    callbacks=[early_stopping])

# Evaluate the model and get the loss and accuracy
test_loss, test_accuracy = model.evaluate(X_test, y_test)

# Print the loss and accuracy
print(f"Test Loss: {test_loss * 100:.2f}%") # access the value from model evaluate
print(f"Test Accuracy: {test_accuracy * 100:.2f}%") # access the value from model evaluate

# Display evaluation metrics
y_pred = (model.predict(X_test) > 0.5).astype("int32")  # Get binary predictions

# Display evaluation metrics
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

# Get the last recorded training loss and accuracy
last_train_loss = history.history['loss'][-1]
last_train_accuracy = history.history['accuracy'][-1]

print(f"Final Training Loss: {last_train_loss * 100:.2f}%") # access the value from history
print(f"Final Training Accuracy: {last_train_accuracy * 100:.2f}%")# access the value from history

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, model.predict(X_test))
print(f"ROC-AUC Score: {roc_auc:.4f}")

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, Bidirectional, LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras.models import Model

file_path = '/content/drive/MyDrive/ROCO_data/data/train/radiology/captions.txt'
with open(file_path, 'r') as file:
    captions = file.readlines()

corpus = [caption.strip() for caption in captions[:300] if caption.strip()]
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocabulary size: {vocab_size}")

# Create sequences from the corpus
sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        ngram_sequence = token_list[:i+1]
        sequences.append(ngram_sequence)

# Find the maximum sequence length
max_sequence_len = max([len(seq) for seq in sequences])
sequences = pad_sequences(sequences, maxlen=max_sequence_len, padding="pre")

X = sequences[:, :-1]
y = sequences[:, -1]
y = to_categorical(y, num_classes=vocab_size)

from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dropout, Dense, Bidirectional
from keras.optimizers import Adam, RMSprop

# Function to build the model with hyperparameters
def build_model(vocab_size, max_sequence_len, embedding_dim=50, lstm_units=100,
                dropout_rate=0.2, optimizer='adam', learning_rate=0.001,
                output_units=None, output_activation='softmax', bidirectional=False):
    """
    Builds an LSTM model with specified hyperparameters.

    Parameters:
    - vocab_size (int): Size of the vocabulary (number of unique tokens).
    - max_sequence_len (int): Maximum length of input sequences.
    - embedding_dim (int): Dimension of the embedding layer.
    - lstm_units (int): Number of LSTM units.
    - dropout_rate (float): Dropout rate to prevent overfitting.
    - optimizer (str): Optimizer to use ('adam' or 'rmsprop').
    - learning_rate (float): Learning rate for the optimizer.
    - output_units (int): Number of units in the output layer. Defaults to vocab_size for multi-class.
    - output_activation (str): Activation function for the output layer ('softmax' or 'sigmoid').
    - bidirectional (bool): Whether to use a bidirectional LSTM.

    Returns:
    - model (keras.Model): Compiled LSTM model.
    """

    # Select optimizer with specified learning rate
    if optimizer == 'adam':
        selected_optimizer = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        selected_optimizer = RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError("Unsupported optimizer. Use 'adam' or 'rmsprop'.")

    # Build the model
    model = Sequential()

    # Embedding layer
    model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_sequence_len-1))

    # LSTM layer (Bidirectional if specified)
    if bidirectional:
        model.add(Bidirectional(LSTM(lstm_units, return_sequences=False)))
    else:
        model.add(LSTM(lstm_units, return_sequences=False))

    # Dropout layer
    model.add(Dropout(dropout_rate))

    # Output layer
    if output_units is None:
        output_units = vocab_size  # Default for multi-class classification
    model.add(Dense(output_units, activation=output_activation))

    # Compile the model
    model.compile(loss="categorical_crossentropy" if output_activation == 'softmax' else 'binary_crossentropy',
                  optimizer=selected_optimizer,
                  metrics=['accuracy'])

    return model

# Define hyperparameters
hyperparameters = {
    "embedding_dim": 100,  # Dimension of embedding vector
    "lstm_units": 128,     # Number of LSTM units
    "dropout_rate": 0.3,   # Dropout rate
    "optimizer": 'adam',   # Optimizer type ('adam' or 'rmsprop')
    "learning_rate": 0.001 # Learning rate
}

from keras.models import Model
from keras.layers import Input, Embedding, LSTM, Bidirectional, BatchNormalization, Dense, Dropout
from keras.optimizers import Adam

# Build model function
def build_model(embedding_dim, lstm_units, dropout_rate, optimizer='adam', learning_rate=0.001, input_shape=(None,), dense_units=128):
    """
    Builds an improved LSTM model with specified hyperparameters.

    Parameters:
    - embedding_dim (int): Dimension of the embedding layer.
    - lstm_units (int): Number of LSTM units in the Bidirectional LSTM layer.
    - dropout_rate (float): Dropout rate to prevent overfitting.
    - optimizer (str): Optimizer to use ('adam' by default).
    - learning_rate (float): Learning rate for the optimizer.
    - input_shape (tuple): Shape of the input data (default is (None,)).
    - dense_units (int): Number of units in the Dense layer (default is 128).

    Returns:
    - model (keras.Model): Compiled LSTM model.
    """

    # Input layer
    inputs = Input(shape=input_shape, name="input_layer")

    # Embedding layer
    x = Embedding(input_dim=5000, output_dim=embedding_dim, name="embedding_layer")(inputs)

    # Bidirectional LSTM
    x = Bidirectional(LSTM(units=lstm_units, return_sequences=False, dropout=dropout_rate), name="bi_lstm")(x)

    # Batch Normalization
    x = BatchNormalization(name="batch_norm")(x)

    # Dense layer
    x = Dense(units=dense_units, activation='relu', name="dense_layer")(x)

    # Dropout layer
    x = Dropout(rate=dropout_rate, name="dropout_layer")(x)

    # Multi-class output layer
    outputs = Dense(units=2187, activation='softmax', name="output_layer")(x)

    # Model definition
    model = Model(inputs=inputs, outputs=outputs, name="improved_lstm_model")

    # Optimizer with gradient clipping
    if optimizer == 'adam':
        optimizer = Adam(learning_rate=learning_rate, clipnorm=1.0)
    else:
        raise ValueError("Unsupported optimizer. Use 'adam'.")

    # Compile model
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

    return model

# Build the updated model using hyperparameters from a dictionary
model = build_model(
    embedding_dim=hyperparameters['embedding_dim'],
    lstm_units=hyperparameters['lstm_units'],
    dropout_rate=hyperparameters['dropout_rate'],
    optimizer=hyperparameters['optimizer'],
    learning_rate=hyperparameters['learning_rate']
)

# Model summary
model.summary()

from keras.callbacks import EarlyStopping, ModelCheckpoint

# Define early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Define a model checkpoint to save the best model with the correct file extension
model_checkpoint = ModelCheckpoint(
    'best_model.keras',  # Changed to .keras extension
    monitor='val_loss',
    save_best_only=True,
    mode='min'
)

# Train the model and capture the history
print("\nTraining Model:")
history = model.fit(
    X,
    y,
    epochs=100,
    verbose=1,
    batch_size=32,
    validation_split=0.2,  # Use 20% of data for validation
    callbacks=[early_stopping, model_checkpoint]  # Include callbacks
)

# Optionally plot the training history
import matplotlib.pyplot as plt

# Plot training & validation loss values
plt.figure(figsize=(12, 6))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(loc='upper right')
plt.grid()
plt.show()

# Plot training & validation accuracy values
plt.figure(figsize=(12, 6))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(loc='upper left')
plt.grid()
plt.show()

final_accuracy = history.history['accuracy'][-1]  # Get the final accuracy from the history
print(f"\ Accuracy : {final_accuracy*100}")

"""**Classification report of LSTM**"""

from sklearn.metrics import classification_report
import numpy as np

# Predict the classes for the training data
y_pred = np.argmax(model.predict(X), axis=-1)  # Convert softmax probabilities to class indices
y_true = np.argmax(y, axis=-1)  # Convert one-hot encoded true labels to class indices

# Get the unique class labels from y_true
labels = np.unique(y_true)

# Filter target_names to match the labels
target_names = [tokenizer.index_word.get(label, str(label)) for label in labels]


# Generate the classification report using the filtered target_names and labels
report = classification_report(y_true, y_pred, labels=labels, target_names=target_names)
print("\nClassification Report:\n")
print(report)

"""**HYPERPARAMETER TUNING**

**Randomized search**
"""

from sklearn.model_selection import ParameterSampler, train_test_split
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

# Define the hyperparameter space
param_space = {
    "embedding_dim": [50, 100, 150],
    "lstm_units": [64, 128, 256],
    "dropout_rate": [0.2, 0.3, 0.5],
    "optimizer": ['adam', 'rmsprop'],
    "learning_rate": [0.001, 0.005, 0.01]
}

# Randomized search configuration
n_iter = 10  # Number of random combinations to try
param_combinations = list(ParameterSampler(param_space, n_iter=n_iter, random_state=42))

# Ensure X and y are preprocessed correctly (replace X, y with actual data)
# Example: Ensure X is 2D and y is 1D
assert len(X) == len(y), "Mismatch in the number of samples between X and y."

# Splitting data into training and validation
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Verify and log shapes for debugging
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}, y_val shape: {y_val.shape}")

# Reshape target labels for binary classification (if necessary)
if len(y_train.shape) == 1:
    y_train = y_train.reshape(-1, 1)
    y_val = y_val.reshape(-1, 1)

# Initialize tracking variables
best_accuracy = 0
best_params = None
best_model = None

# Function to build the model
def build_model(embedding_dim, lstm_units, dropout_rate, optimizer, learning_rate):
    from tensorflow.keras import Sequential
    from tensorflow.keras.layers import Embedding, LSTM, Dropout, Dense
    from tensorflow.keras.optimizers import Adam, RMSprop

    model = Sequential([
        Embedding(input_dim=X_train.shape[1], output_dim=embedding_dim, input_length=X_train.shape[1]),
        LSTM(lstm_units, return_sequences=False),
        Dropout(dropout_rate),
        Dense(1, activation='sigmoid')
    ])

    optimizer_instance = Adam(learning_rate=learning_rate) if optimizer == 'adam' else RMSprop(learning_rate=learning_rate)
    model.compile(optimizer=optimizer_instance, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Run randomized search experiments
for idx, params in enumerate(param_combinations):
    print(f"\n[{idx + 1}/{n_iter}] Testing combination: {params}")

    # Build model with current parameters
    model = build_model(
        embedding_dim=params['embedding_dim'],
        lstm_units=params['lstm_units'],
        dropout_rate=params['dropout_rate'],
        optimizer=params['optimizer'],
        learning_rate=params['learning_rate']
    )

    # Define early stopping
    early_stopping = EarlyStopping(monitor='val_accuracy', patience=3, restore_best_weights=True, verbose=1)

    # Train the model
    try:
        history = model.fit(
            X_train, y_train,
            validation_data=(X_val, y_val),
            epochs=20,
            batch_size=32,
            callbacks=[early_stopping],
            verbose=0  # Suppress detailed logs
        )

        # Get the best validation accuracy
        val_accuracy = max(history.history['val_accuracy'])
        print(f"Validation Accuracy: {val_accuracy:.4f}")

        # Update best model if current one is better
        if val_accuracy > best_accuracy:
            best_accuracy = val_accuracy
            best_params = params
            best_model = model
    except ValueError as e:
        print(f"Error during training: {e}")

# Display the results
print("\n--- Randomized Search Results ---")
print(f"Best Parameters: {best_params}")
print(f"Best Validation Accuracy: {best_accuracy:.4f}")

# Save the best model
if best_model:
    best_model.save("best_model.h5")
    print("\nBest model saved as 'best_model.h5'.")
else:
    print("No model was successfully trained.")

"""**Hyperopt**

"""

from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
import numpy as np

# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Function to build the model
def build_model(embedding_dim, lstm_units, dropout_rate, optimizer, learning_rate):
    from tensorflow.keras import Sequential
    from tensorflow.keras.layers import Embedding, LSTM, Dropout, Dense
    from tensorflow.keras.optimizers import Adam, RMSprop

    model = Sequential([
        Embedding(input_dim=X_train.shape[1], output_dim=embedding_dim, input_length=X_train.shape[1]),
        LSTM(lstm_units, return_sequences=False),
        Dropout(dropout_rate),
        Dense(1, activation='sigmoid')
    ])

    optimizer_instance = Adam(learning_rate=learning_rate) if optimizer == 'adam' else RMSprop(learning_rate=learning_rate)
    model.compile(optimizer=optimizer_instance, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Define the objective function
def objective(params):
    print(f"Testing combination: {params}")

    # Build model with dynamic parameter casting
    model = build_model(
        embedding_dim=int(params['embedding_dim']),
        lstm_units=int(params['lstm_units']),
        dropout_rate=params['dropout_rate'],
        optimizer=params['optimizer'],
        learning_rate=params['learning_rate']
    )

    # Define early stopping
    early_stopping = EarlyStopping(monitor='val_accuracy', patience=3, restore_best_weights=True, verbose=0)

    # Train the model
    try:
        history = model.fit(
            X_train, y_train,
            validation_data=(X_val, y_val),
            epochs=20,  # More epochs with early stopping
            batch_size=32,
            callbacks=[early_stopping],
            verbose=0  # Suppress detailed training logs
        )

        # Get the best validation accuracy
        val_accuracy = max(history.history['val_accuracy'])
        print(f"Validation Accuracy: {val_accuracy:.4f}")

        # Return the negative of validation accuracy as loss for Hyperopt
        return {'loss': -val_accuracy, 'status': STATUS_OK}
    except ValueError as e:
        print(f"Error during training: {e}")
        return {'loss': float('inf'), 'status': STATUS_OK}

# Define the search space
space = {
    'embedding_dim': hp.choice('embedding_dim', [50, 100, 150]),
    'lstm_units': hp.choice('lstm_units', [64, 128, 256]),
    'dropout_rate': hp.uniform('dropout_rate', 0.2, 0.5),
    'optimizer': hp.choice('optimizer', ['adam', 'rmsprop']),
    'learning_rate': hp.loguniform('learning_rate', np.log(0.001), np.log(0.01))
}

# Run Hyperopt
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=20, trials=trials)

print("\n--- Hyperopt Results ---")
print(f"Best Parameters: {best}")

# Map integer indices to actual parameter values for categorical choices
best_params = {
    'embedding_dim': [50, 100, 150][best['embedding_dim']],
    'lstm_units': [64, 128, 256][best['lstm_units']],
    'dropout_rate': best['dropout_rate'],
    'optimizer': ['adam', 'rmsprop'][best['optimizer']],
    'learning_rate': best['learning_rate']
}
print(f"Best Parameters (Decoded): {best_params}")

print("\nTrials Summary:")
for trial in trials.trials[:5]:  # Print the first 5 trials for brevity
    print(f"Trial {trial['tid']}: Loss={trial['result']['loss']}, Params={trial['misc']['vals']}")

"""**Grid Search**"""

from itertools import product
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the hyperparameter grid
param_grid = {
    "embedding_dim": [50, 100],
    "lstm_units": [64, 128],
    "dropout_rate": [0.2, 0.3],
    "optimizer": ['adam'],
    "learning_rate": [0.001, 0.005]
}

# Generate all combinations
param_combinations = list(product(*param_grid.values()))

# Function to build the model
def build_model(embedding_dim, lstm_units, dropout_rate, optimizer, learning_rate):
    from tensorflow.keras import Sequential
    from tensorflow.keras.layers import Embedding, LSTM, Dropout, Dense
    from tensorflow.keras.optimizers import Adam, RMSprop

    model = Sequential([
        Embedding(input_dim=X_train.shape[1], output_dim=embedding_dim, input_length=X_train.shape[1]),
        LSTM(lstm_units, return_sequences=False),
        Dropout(dropout_rate),
        Dense(1, activation='sigmoid')
    ])

    optimizer_instance = Adam(learning_rate=learning_rate) if optimizer == 'adam' else RMSprop(learning_rate=learning_rate)
    model.compile(optimizer=optimizer_instance, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Initialize variables to track the best results
best_accuracy = 0
best_params = None

# Early stopping callback
early_stopping = EarlyStopping(monitor='val_accuracy', patience=3, restore_best_weights=True, verbose=0)

# Grid Search
print(f"Total combinations to test: {len(param_combinations)}")
for idx, param_set in enumerate(param_combinations, start=1):
    params = dict(zip(param_grid.keys(), param_set))
    print(f"\n[{idx}/{len(param_combinations)}] Testing combination: {params}")

    # Build the model with the current parameter combination
    model = build_model(**params)

    # Train the model
    try:
        history = model.fit(
            X_train, y_train,
            validation_data=(X_val, y_val),
            epochs=10,  # Set a higher number of epochs with early stopping
            batch_size=32,
            callbacks=[early_stopping],
            verbose=0  # Suppress detailed logs for each epoch
        )

        # Get the best validation accuracy
        val_accuracy = max(history.history['val_accuracy'])
        print(f"Validation Accuracy: {val_accuracy:.4f}")

        # Update best parameters if the current combination is better
        if val_accuracy > best_accuracy:
            best_accuracy = val_accuracy
            best_params = params
    except ValueError as e:
        print(f"Error during training with parameters {params}: {e}")

# Print the best parameters and accuracy
print("\n--- Grid Search Results ---")
print(f"Best Parameters: {best_params}")
print(f"Best Validation Accuracy: {best_accuracy:.4f}")

"""**Bleu Score**"""

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

# Example function to generate text based on the model
def generate_text(seed_text, max_sequence_len, tokenizer, model, n_words=5):
    for _ in range(n_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
        predicted_probs = model.predict(token_list, verbose=0)
        predicted_index = np.argmax(predicted_probs)
        predicted_word = tokenizer.index_word[predicted_index] if predicted_index in tokenizer.index_word else ''
        seed_text += ' ' + predicted_word
    return seed_text.strip()

# Test on the corpus and compute BLEU scores
smooth_fn = SmoothingFunction().method1  # Smoothing for BLEU
bleu_scores = []

print("\nEvaluating BLEU Score:")
for i, caption in enumerate(corpus):
    seed_text = ' '.join(caption.split()[:2])  # Take the first 2 words as seed
    generated_text = generate_text(seed_text, max_sequence_len, tokenizer, model, n_words=5)
    reference = [caption.split()]  # BLEU expects a list of references
    candidate = generated_text.split()
    bleu_score = sentence_bleu(reference, candidate, smoothing_function=smooth_fn)
    bleu_scores.append(bleu_score)
    print(f"Caption {i+1}:")
    print(f"  Reference: {caption}")
    print(f"  Generated: {generated_text}")
    print(f"  BLEU Score: {bleu_score:.4f}")

# Compute the average BLEU score
average_bleu = np.mean(bleu_scores)
print(f"\nAverage BLEU Score: {average_bleu:.4f}")

"""**IMAGE CAPTIONING**

"""

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, Dropout, Add
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np
import pandas as pd

image_paths_file = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/images'
captions_file = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/images'

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import random


image_dir = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/images'
captions_file = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/captions.txt'

try:

    image_paths = [
        os.path.join(image_dir, filename)
        for filename in os.listdir(image_dir)
        if filename.lower().endswith(('.jpg', '.png', '.jpeg'))
    ]


    if os.path.exists(captions_file):
        with open(captions_file, 'r', encoding='utf-8') as f:
            captions = [line.strip() for line in f if line.strip()]
    else:
        raise FileNotFoundError(f"Captions file not found at: {captions_file}")

    min_len = min(len(image_paths), len(captions))
    if min_len == 0:
        raise ValueError("No valid image-caption pairs found.")


    sample_size = min(min_len, 9)  # Display up to 9 images in a 3x3 grid
    sampled_indices = random.sample(range(min_len), sample_size)
    sampled_image_paths = [image_paths[i] for i in sampled_indices]
    sampled_captions = [captions[i] for i in sampled_indices]

    plt.figure(figsize=(12, 12))
    for i, (image_path, caption) in enumerate(zip(sampled_image_paths, sampled_captions)):
        try:
            img = mpimg.imread(image_path)
            plt.subplot(3, 3, i + 1)  # 3 rows, 3 columns
            plt.imshow(img)
            plt.axis('off')
            plt.title(f"{caption}\nSize: {img.shape[0]}x{img.shape[1]}", fontsize=10)
        except Exception as e:
            print(f"Error displaying image {image_path}: {e}")

    plt.tight_layout()
    plt.show()

except Exception as e:
    print(f"An error occurred: {e}")

image_captions = {}
for img, cap in zip(image_paths, captions):
    if img not in image_captions:
        image_captions[img] = []
    image_captions[img].append(cap)

# Print the image paths and their associated captions
for img, caps in image_captions.items():
    print(f"Image: {img}")
    print("Captions:")
    for caption in caps:
        print(f"- {caption}")
    print("-" * 40)

all_captions = [caption for captions in image_captions.values() for caption in captions]
all_captions[:5]

all_captions = [caption for captions in image_captions.values() for caption in captions]

print("All Captions:")
for i, caption in enumerate(all_captions, 1):
    print(f"{i}. {caption}")

"""**CAPTION PREPROCESSING AND FEATURE EXTRACTION**"""

from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

def preprocess_captions(captions):
    """
    Preprocesses the captions by tokenizing and converting them to sequences.

    Args:
        captions (list of str): List of captions to be preprocessed.

    Returns:
        tuple: Contains the tokenizer, sequences, maximum sequence length,
               vocabulary size, average sequence length, and inverse word index.
    """
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(captions)
    sequences = tokenizer.texts_to_sequences(captions)
    max_length = max(len(seq) for seq in sequences)
    vocab_size = len(tokenizer.word_index) + 1
    avg_length = np.mean([len(seq) for seq in sequences])
    inverse_word_index = {index: word for word, index in tokenizer.word_index.items()}
    return tokenizer, sequences, max_length, vocab_size, avg_length, inverse_word_index


tokenizer, sequences, max_length, vocab_size, avg_length, inverse_word_index = preprocess_captions(all_captions)


print("Preprocessing Results:")
print(f"Total Captions Processed: {len(all_captions)}")
print(f"Vocabulary Size: {vocab_size}")
print(f"Maximum Sequence Length: {max_length}")
print(f"Average Sequence Length: {avg_length:.2f}")
print("\nSample Sequences (first 5):")
for i, seq in enumerate(sequences[:5], 1):
    print(f"{i}. {seq}")

print("\nWord Index (first 10 words):")
for word, index in list(tokenizer.word_index.items())[:10]:
    print(f"{word}: {index}")

print("\nInverse Word Index (first 10 indices):")
for index in range(1, 11):  # Display the first 10 indices
    print(f"{index}: {inverse_word_index.get(index, 'N/A')}")

import tensorflow as tf
import numpy as np
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.models import Model
import random
import os
import tqdm
import matplotlib.pyplot as plt

def extract_features(image_paths, model, batch_size=16):
    """
    Extracts features from a list of image paths using a pre-trained model.

    Args:
        image_paths (list of str): List of paths to images.
        model (tf.keras.Model): Pre-trained Keras model for feature extraction.
        batch_size (int): Number of images to process in each batch.

    Returns:
        dict: Dictionary mapping image paths to their extracted features.
    """
    features = {}
    for batch_start in tqdm.tqdm(range(0, len(image_paths), batch_size), desc="Processing Batches"):
        batch_paths = image_paths[batch_start:batch_start + batch_size]
        batch_imgs = []

        for path in batch_paths:
            try:
                img = tf.keras.preprocessing.image.load_img(path, target_size=(299, 299))
                img = tf.keras.preprocessing.image.img_to_array(img)
                batch_imgs.append(img)
            except Exception as e:
                print(f"Error loading image {path}: {e}")
                continue

        if not batch_imgs:
            continue

        batch_imgs = np.array(batch_imgs)
        batch_imgs = preprocess_input(batch_imgs)
        batch_features = model.predict(batch_imgs, verbose=0)

        for path, feat in zip(batch_paths, batch_features):
            features[path] = feat
    return features


image_model = InceptionV3(weights="imagenet")
image_model = Model(inputs=image_model.input, outputs=image_model.layers[-2].output)


random_image_paths = random.sample(image_paths, 10)


image_features = extract_features(random_image_paths, image_model)

for image_path, features in image_features.items():
    print(f"Image: {os.path.basename(image_path)}")
    print(f"Features Shape: {features.shape}")
    print(f"Features (first 10 values): {features[:10]}")  # Print only first 10 values
    print("-" * 40)


def display_images_with_features(image_paths, features_dict):
    """
    Displays images along with their extracted features.

    Args:
        image_paths (list of str): List of image paths.
        features_dict (dict): Dictionary of features for the images.
    """
    plt.figure(figsize=(15, 10))
    for i, image_path in enumerate(image_paths):
        img = tf.keras.preprocessing.image.load_img(image_path)
        plt.subplot(2, 5, i + 1)
        plt.imshow(img)
        plt.axis('off')
        plt.title(f"Features: {features_dict[image_path][:5]}")
    plt.tight_layout()
    plt.show()


display_images_with_features(random_image_paths, image_features)

"""LSTM MODEL FOR CAPTIONING"""

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, Add, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam


def create_model(vocab_size, max_length, dropout_rate=0.5):
    """
    Creates a model that combines image features and text input.

    Args:
        vocab_size (int): Size of the vocabulary for text input.
        max_length (int): Maximum length of the text input sequences.
        dropout_rate (float): Dropout rate to prevent overfitting.

    Returns:
        Model: Keras model combining image and text inputs.
    """

    image_input = Input(shape=(2048,), name="image_input")
    image_dense = Dense(256, activation="relu", name="image_dense")(image_input)
    image_dense = BatchNormalization(name="image_batch_norm")(image_dense)
    image_dense = Dropout(dropout_rate, name="image_dropout")(image_dense)


    text_input = Input(shape=(max_length,), name="text_input")
    text_embedding = Embedding(vocab_size, 256, mask_zero=True, name="text_embedding")(text_input)
    text_lstm = LSTM(256, return_sequences=True, dropout=dropout_rate, recurrent_dropout=dropout_rate, name="text_lstm")(text_embedding)
    text_lstm = LSTM(256, dropout=dropout_rate, recurrent_dropout=dropout_rate, name="text_lstm_2")(text_lstm)


    decoder = Add(name="add_layer")([image_dense, text_lstm])
    decoder_dense = Dense(256, activation="relu", name="decoder_dense")(decoder)
    decoder_dense = Dropout(dropout_rate, name="decoder_dropout")(decoder_dense)
    output = Dense(vocab_size, activation="softmax", name="output")(decoder_dense)
    model = Model(inputs=[image_input, text_input], outputs=output)
    model.summary()
    return model
model = create_model(vocab_size, max_length)
optimizer = Adam(learning_rate=0.001, clipnorm=1.0)
model.compile(loss="categorical_crossentropy", optimizer=optimizer, metrics=["accuracy"])

from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
import os

def data_generator(image_features, caption_path, tokenizer, max_length, vocab_size):

    with open(caption_path, 'r', encoding='utf-8') as f:
        captions = [line.strip() for line in f]

    while True:
        for i, (image_id, image_feature) in enumerate(image_features.items()):
            if i >= len(captions):
                break
            caption = captions[i]
            seq = tokenizer.texts_to_sequences([caption])[0]
            for j in range(1, len(seq)):
                input_seq = seq[:j]
                output_word = seq[j]

                input_seq_padded = pad_sequences([input_seq], maxlen=max_length, padding='post')[0]

                image_feature_tensor = tf.convert_to_tensor(image_feature[0], dtype=tf.float32)
                input_seq_tensor = tf.convert_to_tensor(input_seq_padded, dtype=tf.float32)
                output_word_tensor = tf.keras.utils.to_categorical([output_word], num_classes=vocab_size)[0]
                output_word_tensor = tf.convert_to_tensor(output_word_tensor, dtype=tf.float32)

                yield (image_feature_tensor, input_seq_tensor), output_word_tensor

def test_generator_with_captions():
    image_features = {
        "image_1": [tf.random.uniform((2048,))],
        "image_2": [tf.random.uniform((2048,))],
    }
    captions_file_path = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/captions.txt'

    if not os.path.exists(captions_file_path):
        print(f"Captions file not found: {captions_file_path}")
        return

    tokenizer = tf.keras.preprocessing.text.Tokenizer()
    with open(captions_file_path, 'r', encoding='utf-8') as f:
        all_captions = [line.strip() for line in f]
    tokenizer.fit_on_texts(all_captions)

    max_length = max(len(caption.split()) for caption in all_captions)
    vocab_size = len(tokenizer.word_index) + 1

    gen = data_generator(image_features, captions_file_path, tokenizer, max_length, vocab_size)

    for _ in range(5):
        (image_feature_tensor, input_seq_tensor), output_word_tensor = next(gen)
        print(f"Image Feature Tensor: {image_feature_tensor.numpy()[:10]}")
        print(f"Input Sequence Tensor: {input_seq_tensor.numpy()}")
        print(f"Output Word Tensor: {output_word_tensor.numpy()}")
        print("-" * 40)
test_generator_with_captions()

"""**FEATURE EXTRACTION USING DIFFERENT PRETRAINED MODEL**"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import ResNet50, VGG16, VGG19
from tensorflow.keras.applications.vgg16 import preprocess_input as vgg16_preprocess
from tensorflow.keras.applications.vgg19 import preprocess_input as vgg19_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess
from tensorflow.keras.applications.imagenet_utils import decode_predictions
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import matplotlib.pyplot as plt
import cv2
import os

def preprocess_image(image_path, model_type):
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Image file not found: {image_path}")

    img = load_img(image_path, target_size=(224, 224))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)

    if model_type == 'resnet':
        return resnet_preprocess(img_array)
    elif model_type == 'vgg16':
        return vgg16_preprocess(img_array)
    elif model_type == 'vgg19':
        return vgg19_preprocess(img_array)
    else:
        return img_array

def extract_block_features(image_path, model, block_name, model_type):
    preprocessed_img = preprocess_image(image_path, model_type)
    intermediate_layer_model = tf.keras.Model(
        inputs=model.input, outputs=model.get_layer(block_name).output
    )
    feature_map = intermediate_layer_model.predict(preprocessed_img)
    return feature_map

def visualize_block_features(feature_map, block_name, num_features=5):
    feature_map = feature_map.squeeze()
    feature_map_mean = np.mean(feature_map, axis=(0, 1))
    top_features_idx = np.argsort(feature_map_mean)[-num_features:]

    print(f"Block: {block_name}")
    print("Top 5 feature indices (sorted by mean activation):", top_features_idx)
    print("Top 5 feature mean activations:", feature_map_mean[top_features_idx])

    plt.figure(figsize=(15, 10))
    for i, idx in enumerate(top_features_idx):
        plt.subplot(1, num_features, i + 1)
        plt.imshow(cv2.GaussianBlur(feature_map[:, :, idx], (5, 5), 0), cmap='viridis')
        plt.title(f'{block_name} Feature {idx + 1}')
        plt.axis('off')
    plt.show()

def get_top_5_predictions(image_path, model, model_type):
    preprocessed_img = preprocess_image(image_path, model_type)
    preds = model.predict(preprocessed_img)
    decoded_preds = decode_predictions(preds, top=5)[0]

    print(f"\nTop 5 Predictions for {model_type}:")
    for i, (imagenet_id, label, prob) in enumerate(decoded_preds):
        print(f"{i + 1}. {label}: {prob * 100:.2f}%")

resnet_model = ResNet50(weights='imagenet', include_top=True)
vgg16_model = VGG16(weights='imagenet', include_top=True)
vgg19_model = VGG19(weights='imagenet', include_top=True)

image_path = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/images/ROCO_87946.jpg'

blocks = {
    'resnet': ['conv1_conv', 'conv2_block1_out', 'conv3_block1_out'],
    'vgg16': ['block1_conv2', 'block2_conv2', 'block3_conv3'],
    'vgg19': ['block1_conv2', 'block2_conv2', 'block3_conv4']
}


print("Processing ResNet50...")
for block in blocks['resnet']:
    resnet_features = extract_block_features(image_path, resnet_model, block, 'resnet')
    visualize_block_features(resnet_features, block)
    get_top_5_predictions(image_path, resnet_model, 'resnet')

# VGG16
print("Processing VGG16...")
for block in blocks['vgg16']:
    vgg16_features = extract_block_features(image_path, vgg16_model, block, 'vgg16')
    visualize_block_features(vgg16_features, block)
    get_top_5_predictions(image_path, vgg16_model, 'vgg16')

# VGG19
print("Processing VGG19...")
for block in blocks['vgg19']:
    vgg19_features = extract_block_features(image_path, vgg19_model, block, 'vgg19')
    visualize_block_features(vgg19_features, block)
    get_top_5_predictions(image_path, vgg19_model, 'vgg19')

"""CAPTION GENERATION.."""

import numpy as np
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam, RMSprop
import matplotlib.pyplot as plt

file_path = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/captions.txt'


with open(file_path, 'r') as file:
    all_captions = file.readlines()

corpus = [caption.strip() for caption in all_captions[:10] if caption.strip()]

image_dir = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/images'
captions_file = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/captions.txt'

image_paths = [os.path.join(image_dir, filename) for filename in os.listdir(image_dir) if filename.endswith(('.jpg', '.png'))]

with open(captions_file, 'r') as f:
    captions = [line.strip() for line in f]

min_len = min(len(image_paths), len(captions))
image_paths = image_paths[:min_len]
captions = captions[:min_len]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocabulary size: {vocab_size}")

sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        ngram_sequence = token_list[:i + 1]
        sequences.append(ngram_sequence)

max_sequence_len = max([len(seq) for seq in sequences])
sequences = pad_sequences(sequences, maxlen=max_sequence_len, padding="pre")

X = sequences[:, :-1]
y = sequences[:, -1]
y = to_categorical(y, num_classes=vocab_size)

hyperparameters = {
    "embedding_dim": 100,
    "lstm_units": 128,
    "dropout_rate": 0.3,
    "optimizer": 'adam',
    "learning_rate": 0.001
}

def build_model(embedding_dim=100, lstm_units=128, dropout_rate=0.3, optimizer='adam', learning_rate=0.001):
    if optimizer == 'adam':
        selected_optimizer = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        selected_optimizer = RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError("Unsupported optimizer. Use 'adam' or 'rmsprop'.")

    model = Sequential([
        Embedding(vocab_size, embedding_dim, input_length=max_sequence_len - 1),
        LSTM(lstm_units, return_sequences=False),
        Dropout(dropout_rate),
        Dense(vocab_size, activation="softmax")
    ])
    model.compile(loss="categorical_crossentropy", optimizer=selected_optimizer, metrics=['accuracy'])
    return model

model = build_model(
    embedding_dim=hyperparameters['embedding_dim'],
    lstm_units=hyperparameters['lstm_units'],
    dropout_rate=hyperparameters['dropout_rate'],
    optimizer=hyperparameters['optimizer'],
    learning_rate=hyperparameters['learning_rate']
)

print("\nTraining Model:")
history = model.fit(X, y, epochs=100, verbose=1, batch_size=32)

def generate_caption(image_caption, max_words=8):
    seed_text = image_caption.split()[0]
    generated_text = seed_text

    for _ in range(max_words):
        token_list = tokenizer.texts_to_sequences([generated_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len - 1, padding="pre")
        predicted = np.argmax(model.predict(token_list, verbose=0), axis=-1)

        output_word = next((word for word, index in tokenizer.word_index.items() if index == predicted), None)
        if output_word:
            generated_text += " " + output_word

        if generated_text in corpus:
            break

    return generated_text.strip()

original_caption = captions[5]
generated_caption = generate_caption(original_caption)
print(f"\nOriginal Caption: {original_caption}")
print(f"Generated Caption: {generated_caption}")

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam, RMSprop

file_path ='/content/drive/MyDrive/ROCO_data/data/train/non-radiology/captions.txt'

with open(file_path, 'r') as file:
    all_captions = file.readlines()

corpus = [caption.strip() for caption in all_captions[:10] if caption.strip()]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocabulary size: {vocab_size}")

sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        ngram_sequence = token_list[:i+1]
        sequences.append(ngram_sequence)

max_sequence_len = max([len(seq) for seq in sequences])
sequences = pad_sequences(sequences, maxlen=max_sequence_len, padding="pre")

X = sequences[:, :-1]
y = sequences[:, -1]
y = to_categorical(y, num_classes=vocab_size)

def build_model(embedding_dim=50, lstm_units=100, dropout_rate=0.2, optimizer='adam', learning_rate=0.001):
    if optimizer == 'adam':
        selected_optimizer = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        selected_optimizer = RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError("Unsupported optimizer. Use 'adam' or 'rmsprop'.")

    model = Sequential([
        Embedding(vocab_size, embedding_dim, input_length=max_sequence_len-1),
        LSTM(lstm_units, return_sequences=False),
        Dropout(dropout_rate),
        Dense(vocab_size, activation="softmax")
    ])
    model.compile(loss="categorical_crossentropy", optimizer=selected_optimizer, metrics=['accuracy'])
    return model

hyperparameters = {
    "embedding_dim": 100,
    "lstm_units": 128,
    "dropout_rate": 0.3,
    "optimizer": 'adam',
    "learning_rate": 0.001
}

print("\nHyperparameters:")
for key, value in hyperparameters.items():
    print(f"{key}: {value}")

model = build_model(
    embedding_dim=hyperparameters['embedding_dim'],
    lstm_units=hyperparameters['lstm_units'],
    dropout_rate=hyperparameters['dropout_rate'],
    optimizer=hyperparameters['optimizer'],
    learning_rate=hyperparameters['learning_rate']
)

print("\nTraining Model:")
history = model.fit(X, y, epochs=100, verbose=1, batch_size=32)

final_accuracy = history.history['accuracy'][-1]
print(f"\nFinal Accuracy after 100 epochs: {final_accuracy}")

"""**HYPERPARAMETER TUNING**"""

pip install optuna

import numpy as np
import os
import optuna
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import matplotlib.pyplot as plt

file_path = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/captions.txt'
with open(file_path, 'r') as file:
    all_captions = file.readlines()

corpus = [caption.strip() for caption in all_captions[:10] if caption.strip()]

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(corpus)
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocabulary size: {vocab_size}")
s
sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        ngram_sequence = token_list[:i + 1]
        sequences.append(ngram_sequence)

max_sequence_len = max(len(seq) for seq in sequences)
sequences = pad_sequences(sequences, maxlen=max_sequence_len, padding="pre")

X = sequences[:, :-1]
y = sequences[:, -1]
y = to_categorical(y, num_classes=vocab_size)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

def objective(trial):
    embedding_dim = trial.suggest_categorical("embedding_dim", [50, 100, 150])
    lstm_units = trial.suggest_categorical("lstm_units", [32, 64, 128])
    dropout_rate = trial.suggest_uniform("dropout_rate", 0.2, 0.5)
    optimizer_name = trial.suggest_categorical("optimizer", ["adam", "rmsprop"])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-4, 1e-2)

    if optimizer_name == "adam":
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_name == "rmsprop":
        optimizer = RMSprop(learning_rate=learning_rate)

    model = Sequential([
        Embedding(vocab_size, embedding_dim, input_length=max_sequence_len - 1),
        LSTM(lstm_units),
        Dropout(dropout_rate),
        Dense(vocab_size, activation="softmax")
    ])
    model.compile(loss="categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

    early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=10,
        batch_size=32,
        verbose=0,
        callbacks=[early_stopping]
    )

    val_accuracy = history.history['val_accuracy'][-1]
    return val_accuracy

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10)

print("\nTuned hyperparameters: ")
for key, value in study.best_params.items():
    print(f"{key}: {value}")

print("\nTuned validation accuracy: ", study.best_value)

best_params = study.best_params
model = Sequential([
    Embedding(vocab_size, best_params["embedding_dim"], input_length=max_sequence_len - 1),
    LSTM(best_params["lstm_units"]),
    Dropout(best_params["dropout_rate"]),
    Dense(vocab_size, activation="softmax")
])
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=best_params["learning_rate"]), metrics=['accuracy'])

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=10,
    batch_size=32,
    verbose=1,
    callbacks=[EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)]
)

plt.figure(figsize=(12, 6))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

!pip install rouge-score

from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer

def evaluate_captions(original_caption, generated_caption):
    bleu_score = sentence_bleu([original_caption.split()], generated_caption.split())
    print(f"\nBLEU Score: {bleu_score:.4f}")

    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
    rouge_score = scorer.score(original_caption, generated_caption)

    print(f"ROUGE Score (ROUGE-1): {rouge_score['rouge1'].fmeasure:.4f}")
    print(f"ROUGE Score (ROUGE-L): {rouge_score['rougeL'].fmeasure:.4f}")

original_caption = "A cat is sitting on a windowsill."
generated_caption = "A cat sits on the windowsill."

evaluate_captions(original_caption, generated_caption)

"""BLEU SCORE

"""

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

image_dir = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/images'
captions_file = '/content/drive/MyDrive/ROCO_data/data/train/non-radiology/captions.txt'

image_paths = [
    os.path.join(image_dir, filename)
    for filename in os.listdir(image_dir)
    if filename.endswith(('.jpg', '.png'))
]

with open(captions_file, 'r') as f:
    captions = [line.strip() for line in f]

min_len = min(len(image_paths), len(captions))
image_paths = image_paths[:min_len]
captions = captions[:min_len]

def display_image_with_caption(image_path, caption):
    img = mpimg.imread(image_path)
    plt.figure(figsize=(6, 6))
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Original Caption: {caption}", fontsize=12)
    plt.show()

selected_image_index = 5
selected_image_path = image_paths[selected_image_index]
original_caption = captions[selected_image_index]

display_image_with_caption(selected_image_path, original_caption)

print(f"Image Path: {selected_image_path}")
print(f"Original Caption: {original_caption}")

corpus = captions
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocabulary Size: {vocab_size}")

# Create sequences for training
sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        ngram_sequence = token_list[:i + 1]
        sequences.append(ngram_sequence)

# Pad sequences to ensure uniform length
max_sequence_len = max([len(seq) for seq in sequences])
sequences = pad_sequences(sequences, maxlen=max_sequence_len, padding="pre")

# Print sequences and their shapes for verification
print(f"Total Sequences: {len(sequences)}")
print(f"Max Sequence Length: {max_sequence_len}")
print(f"Sample Sequence: {sequences[0]}")

from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer

def evaluate_captions(original_caption, generated_caption):
    if not original_caption or not generated_caption:
        print("Error: One of the captions is empty.")
        return

    bleu_score = sentence_bleu([original_caption.split()], generated_caption.split())
    print(f"\nBLEU Score: {bleu_score:.4f}")  # Format to 4 decimal places

    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
    rouge_score = scorer.score(generated_caption, original_caption)

    print(f"ROUGE Score:")
    print(f"  ROUGE-1: {rouge_score['rouge1'].fmeasure:.4f}")
    print(f"  ROUGE-L: {rouge_score['rougeL'].fmeasure:.4f}")

original_caption = "A dog is playing with a ball."
generated_caption = "A dog plays with a ball."

evaluate_captions(original_caption, generated_caption)